
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:6050
 * Running on http://192.168.86.26:6050
2025-06-13 19:27:57,937 - werkzeug - INFO - [33mPress CTRL+C to quit[0m
2025-06-13 19:27:58,348 - bot - INFO - Setup hook started
2025-06-13 19:27:58,550 - cogs.r6 - INFO - R6Cog loaded and commands synced
2025-06-13 19:27:58,551 - bot - INFO - Loaded extension: cogs.r6
2025-06-13 19:27:58,626 - bot - INFO - Loaded extension: cogs.minecraft
2025-06-13 19:27:58,627 - bot - INFO - Loaded extension: cogs.warframe
2025-06-13 19:27:58,629 - cogs.fun - INFO - Loaded 1 trivia scores
2025-06-13 19:27:58,630 - bot - ERROR - Failed to load extension cogs.fun: Extension 'cogs.fun' raised an error: CommandAlreadyRegistered: Command 'hello' already registered.
2025-06-13 19:27:58,632 - bot - INFO - Loaded extension: cogs.alerts
2025-06-13 19:27:58,634 - bot - ERROR - Failed to load extension cogs.alert_cmd: Extension 'cogs.alert_cmd' raised an error: CommandAlreadyRegistered: Command 'alert' already registered.
2025-06-13 19:27:58,635 - cogs.core - INFO - CoreCog loading: creating aiohttp ClientSession
2025-06-13 19:27:58,635 - cogs.core - INFO - CoreCog unloading: closing aiohttp ClientSession
2025-06-13 19:27:58,636 - bot - ERROR - Failed to load extension cogs.core: Extension 'cogs.core' raised an error: CommandAlreadyRegistered: Command 'weather' already registered.
2025-06-13 19:27:58,637 - bot - INFO - Loaded extension: cogs.owner
2025-06-13 19:27:58,637 - bot - INFO - Loaded extension: cogs.frost
2025-06-13 19:27:58,637 - bot - INFO - Force Syncing commands globally...
2025-06-13 19:28:58,576 - bot - INFO - âœ… Commands synced globally
2025-06-13 19:28:58,576 - bot - INFO - Global commands synced. They may take up to 1 hour to appear on Discord clients.
2025-06-13 19:28:58,800 - discord.gateway - INFO - Shard ID None has connected to Gateway (Session ID: c0e2b42fe4c209cc6b0552162b3bd12d).
2025-06-13 19:28:58,800 - bot - INFO - Connected to Discord
2025-06-13 19:29:00,834 - bot - INFO - Logged in as JÃ¤gerBot#6929 (ID: 1376008090968657990)
2025-06-13 19:29:28,579 - cogs.owner - INFO - Manually synced 0 commands globally.
2025-06-13 20:00:56,002 - discord.client - WARNING - PyNaCl is not installed, voice will NOT be supported
2025-06-13 20:00:56,003 - __main__ - INFO - Starting bot...
2025-06-13 20:00:56,003 - discord.client - INFO - logging in using static token
2025-06-13 20:00:56,010 - werkzeug - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:6050
 * Running on http://192.168.86.26:6050
2025-06-13 20:00:56,011 - werkzeug - INFO - [33mPress CTRL+C to quit[0m
2025-06-13 20:00:56,419 - bot - INFO - Setup hook started
2025-06-13 20:00:56,494 - cogs.r6 - INFO - R6Cog loaded and commands synced
2025-06-13 20:00:56,494 - bot - INFO - Loaded extension: cogs.r6
2025-06-13 20:00:56,699 - bot - INFO - Loaded extension: cogs.minecraft
2025-06-13 20:00:56,703 - bot - INFO - Loaded extension: cogs.warframe
2025-06-13 20:00:56,710 - cogs.fun - INFO - Loaded 1 trivia scores
2025-06-13 20:00:56,710 - bot - INFO - Loaded extension: cogs.fun
2025-06-13 20:00:56,716 - bot - INFO - Loaded extension: cogs.alerts
2025-06-13 20:00:56,721 - bot - INFO - Loaded extension: cogs.alert_cmd
2025-06-13 20:00:56,728 - cogs.core - INFO - CoreCog loading: creating aiohttp ClientSession
2025-06-13 20:00:56,728 - bot - INFO - Loaded extension: cogs.core
2025-06-13 20:00:56,729 - bot - INFO - Loaded extension: cogs.owner
2025-06-13 20:00:56,730 - bot - INFO - Loaded extension: cogs.frost
2025-06-13 20:00:56,730 - bot - INFO - Force Syncing commands globally...
2025-06-13 20:00:57,043 - bot - INFO - âœ… Commands synced globally
2025-06-13 20:00:57,043 - bot - INFO - Global commands synced. They may take up to 1 hour to appear on Discord clients.
2025-06-13 20:00:57,328 - discord.gateway - INFO - Shard ID None has connected to Gateway (Session ID: 5309834298f058af6a8d3b898a520d92).
2025-06-13 20:00:57,329 - bot - INFO - Connected to Discord
2025-06-13 20:00:59,390 - bot - INFO - Logged in as JÃ¤gerBot#6929 (ID: 1376008090968657990)
2025-06-13 20:01:37,082 - cogs.owner - INFO - Manually synced 0 commands globally.
2025-06-13 20:09:00,564 - discord.client - WARNING - PyNaCl is not installed, voice will NOT be supported
2025-06-13 20:09:00,565 - __main__ - INFO - Starting bot...
2025-06-13 20:09:00,566 - discord.client - INFO - logging in using static token
2025-06-13 20:09:00,578 - werkzeug - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:6050
 * Running on http://192.168.86.26:6050
2025-06-13 20:09:00,578 - werkzeug - INFO - [33mPress CTRL+C to quit[0m
2025-06-13 20:09:01,108 - bot - INFO - Setup hook started
2025-06-13 20:09:01,222 - cogs.r6 - INFO - R6Cog loaded and commands synced
2025-06-13 20:09:01,222 - bot - INFO - Loaded extension: cogs.r6
2025-06-13 20:09:01,511 - bot - INFO - Loaded extension: cogs.minecraft
2025-06-13 20:09:01,514 - bot - INFO - Loaded extension: cogs.warframe
2025-06-13 20:09:01,523 - cogs.fun - INFO - Loaded 1 trivia scores
2025-06-13 20:09:01,523 - bot - INFO - Loaded extension: cogs.fun
2025-06-13 20:09:01,531 - bot - INFO - Loaded extension: cogs.alerts
2025-06-13 20:09:01,536 - bot - INFO - Loaded extension: cogs.alert_cmd
2025-06-13 20:09:01,545 - cogs.core - INFO - CoreCog loading: creating aiohttp ClientSession
2025-06-13 20:09:01,545 - bot - INFO - Loaded extension: cogs.core
2025-06-13 20:09:01,548 - bot - INFO - Loaded extension: cogs.owner
2025-06-13 20:09:01,550 - bot - INFO - Loaded extension: cogs.frost
2025-06-13 20:09:01,551 - bot - INFO - App commands before sync: [<discord.app_commands.commands.Group object at 0x7fff11d2f690>, <discord.app_commands.commands.Group object at 0x7fff1309d890>, <discord.app_commands.commands.Group object at 0x7fff11b27e50>, <discord.app_commands.commands.Command object at 0x7fff11b66cd0>, <discord.app_commands.commands.Command object at 0x7fff11b66c90>, <discord.app_commands.commands.Command object at 0x7fff11b66d90>, <discord.app_commands.commands.Command object at 0x7fff11b66e10>, <discord.app_commands.commands.Command object at 0x7fff11b66e90>, <discord.app_commands.commands.Command object at 0x7fff11b67150>, <discord.app_commands.commands.Command object at 0x7fff11b67110>, <discord.app_commands.commands.Command object at 0x7fff11b67350>, <discord.app_commands.commands.Command object at 0x7fff11b644d0>, <discord.app_commands.commands.Command object at 0x7fff11b67450>, <discord.app_commands.commands.Command object at 0x7fff11b67650>, <discord.app_commands.commands.Command object at 0x7fff1309d850>, <discord.app_commands.commands.Command object at 0x7fff131b50d0>, <discord.app_commands.commands.Command object at 0x7fff131b6110>, <discord.app_commands.commands.Command object at 0x7fff11c6f110>, <discord.app_commands.commands.Command object at 0x7fff11c6ea90>, <discord.app_commands.commands.Command object at 0x7fff11c6ec50>, <discord.app_commands.commands.Command object at 0x7fff11c6ed10>, <discord.app_commands.commands.Command object at 0x7fff11c6ed90>, <discord.app_commands.commands.Command object at 0x7fff11c6e950>, <discord.app_commands.commands.Command object at 0x7fff11c6fa90>, <discord.app_commands.commands.Command object at 0x7fff11c6c510>]
2025-06-13 20:09:01,551 - bot - INFO - Force Syncing commands globally...
2025-06-13 20:09:01,712 - bot - INFO - âœ… Commands synced globally
2025-06-13 20:09:01,713 - bot - INFO - Global commands synced. They may take up to 1 hour to appear on Discord clients.
2025-06-13 20:09:01,948 - discord.gateway - INFO - Shard ID None has connected to Gateway (Session ID: 7207d0cf94ae6ac1c7310b67a2567d33).
2025-06-13 20:09:01,949 - bot - INFO - Connected to Discord
2025-06-13 20:09:04,004 - bot - INFO - Logged in as JÃ¤gerBot#6929 (ID: 1376008090968657990)
2025-06-13 20:12:15,304 - cogs.owner - INFO - Manually synced 0 commands globally.
2025-06-13 20:12:23,215 - discord.app_commands.tree - ERROR - Ignoring exception in command tree
Traceback (most recent call last):
  File "/home/spoopinatural/jagerbot/venv/lib/python3.11/site-packages/discord/app_commands/tree.py", line 1151, in wrapper
    await self._call(interaction)
  File "/home/spoopinatural/jagerbot/venv/lib/python3.11/site-packages/discord/app_commands/tree.py", line 1283, in _call
    command, options = self._get_app_command_options(data)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/spoopinatural/jagerbot/venv/lib/python3.11/site-packages/discord/app_commands/tree.py", line 1187, in _get_app_command_options
    raise CommandNotFound(name, parents)
discord.app_commands.errors.CommandNotFound: Application command 'image' not found
2025-06-13 20:16:30,374 - discord.client - WARNING - PyNaCl is not installed, voice will NOT be supported
2025-06-13 20:16:30,376 - __main__ - INFO - Starting bot...
2025-06-13 20:16:30,377 - discord.client - INFO - logging in using static token
2025-06-13 20:16:30,385 - werkzeug - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:6050
 * Running on http://192.168.86.26:6050
2025-06-13 20:16:30,386 - werkzeug - INFO - [33mPress CTRL+C to quit[0m
2025-06-13 20:16:44,236 - __main__ - ERROR - Error running bot
Traceback (most recent call last):
  File "/home/spoopinatural/jagerbot/venv/lib/python3.11/site-packages/aiohttp/connector.py", line 1443, in _create_direct_connection
    hosts = await self._resolve_host(host, port, traces=traces)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/spoopinatural/jagerbot/venv/lib/python3.11/site-packages/aiohttp/connector.py", line 1059, in _resolve_host
    return await asyncio.shield(resolved_host_task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/spoopinatural/jagerbot/venv/lib/python3.11/site-packages/aiohttp/connector.py", line 1090, in _resolve_host_with_throttle
    addrs = await self._resolver.resolve(host, port, family=self._family)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/spoopinatural/jagerbot/venv/lib/python3.11/site-packages/aiohttp/resolver.py", line 40, in resolve
    infos = await self._loop.getaddrinfo(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 867, in getaddrinfo
    return await self.run_in_executor(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno -3] Temporary failure in name resolution

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/spoopinatural/jagerbot/main.py", line 45, in main
    await bot.start(config.DISCORD_TOKEN)
  File "/home/spoopinatural/jagerbot/venv/lib/python3.11/site-packages/discord/client.py", line 823, in start
    await self.login(token)
  File "/home/spoopinatural/jagerbot/venv/lib/python3.11/site-packages/discord/client.py", line 652, in login
    data = await self.http.static_login(token)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/spoopinatural/jagerbot/venv/lib/python3.11/site-packages/discord/http.py", line 828, in static_login
    data = await self.request(Route('GET', '/users/@me'))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/spoopinatural/jagerbot/venv/lib/python3.11/site-packages/discord/http.py", line 642, in request
    async with self.__session.request(method, url, **kwargs) as response:
  File "/home/spoopinatural/jagerbot/venv/lib/python3.11/site-packages/aiohttp/client.py", line 1470, in __aenter__
    self._resp: _RetType = await self._coro
                           ^^^^^^^^^^^^^^^^
  File "/home/spoopinatural/jagerbot/venv/lib/python3.11/site-packages/aiohttp/client.py", line 761, in _request
    resp = await handler(req)
           ^^^^^^^^^^^^^^^^^^
  File "/home/spoopinatural/jagerbot/venv/lib/python3.11/site-packages/aiohttp/client.py", line 716, in _connect_and_send_request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/spoopinatural/jagerbot/venv/lib/python3.11/site-packages/aiohttp/connector.py", line 596, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/spoopinatural/jagerbot/venv/lib/python3.11/site-packages/aiohttp/connector.py", line 1120, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/spoopinatural/jagerbot/venv/lib/python3.11/site-packages/aiohttp/connector.py", line 1449, in _create_direct_connection
    raise ClientConnectorDNSError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorDNSError: Cannot connect to host discord.com:443 ssl:default [Temporary failure in name resolution]
2025-06-13 20:17:05,853 - discord.client - WARNING - PyNaCl is not installed, voice will NOT be supported
2025-06-13 20:17:05,854 - __main__ - INFO - Starting bot...
2025-06-13 20:17:05,854 - discord.client - INFO - logging in using static token
2025-06-13 20:17:05,862 - werkzeug - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:6050
 * Running on http://192.168.86.26:6050
2025-06-13 20:17:05,862 - werkzeug - INFO - [33mPress CTRL+C to quit[0m
2025-06-13 20:17:18,125 - __main__ - ERROR - Error running bot
Traceback (most recent call last):
  File "/home/spoopinatural/jagerbot/venv/lib/python3.11/site-packages/aiohttp/connector.py", line 1443, in _create_direct_connection
    hosts = await self._resolve_host(host, port, traces=traces)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/spoopinatural/jagerbot/venv/lib/python3.11/site-packages/aiohttp/connector.py", line 1059, in _resolve_host
    return await asyncio.shield(resolved_host_task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/spoopinatural/jagerbot/venv/lib/python3.11/site-packages/aiohttp/connector.py", line 1090, in _resolve_host_with_throttle
    addrs = await self._resolver.resolve(host, port, family=self._family)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/spoopinatural/jagerbot/venv/lib/python3.11/site-packages/aiohttp/resolver.py", line 40, in resolve
    infos = await self._loop.getaddrinfo(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 867, in getaddrinfo
    return await self.run_in_executor(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno -3] Temporary failure in name resolution

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/spoopinatural/jagerbot/main.py", line 45, in main
    await bot.start(config.DISCORD_TOKEN)
  File "/home/spoopinatural/jagerbot/venv/lib/python3.11/site-packages/discord/client.py", line 823, in start
    await self.login(token)
  File "/home/spoopinatural/jagerbot/venv/lib/python3.11/site-packages/discord/client.py", line 652, in login
    data = await self.http.static_login(token)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/spoopinatural/jagerbot/venv/lib/python3.11/site-packages/discord/http.py", line 828, in static_login
    data = await self.request(Route('GET', '/users/@me'))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/spoopinatural/jagerbot/venv/lib/python3.11/site-packages/discord/http.py", line 642, in request
    async with self.__session.request(method, url, **kwargs) as response:
  File "/home/spoopinatural/jagerbot/venv/lib/python3.11/site-packages/aiohttp/client.py", line 1470, in __aenter__
    self._resp: _RetType = await self._coro
                           ^^^^^^^^^^^^^^^^
  File "/home/spoopinatural/jagerbot/venv/lib/python3.11/site-packages/aiohttp/client.py", line 761, in _request
    resp = await handler(req)
           ^^^^^^^^^^^^^^^^^^
  File "/home/spoopinatural/jagerbot/venv/lib/python3.11/site-packages/aiohttp/client.py", line 716, in _connect_and_send_request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/spoopinatural/jagerbot/venv/lib/python3.11/site-packages/aiohttp/connector.py", line 596, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/spoopinatural/jagerbot/venv/lib/python3.11/site-packages/aiohttp/connector.py", line 1120, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/spoopinatural/jagerbot/venv/lib/python3.11/site-packages/aiohttp/connector.py", line 1449, in _create_direct_connection
    raise ClientConnectorDNSError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorDNSError: Cannot connect to host discord.com:443 ssl:default [Temporary failure in name resolution]
2025-06-13 20:23:53,045 - discord.client - WARNING - PyNaCl is not installed, voice will NOT be supported
2025-06-13 20:23:53,046 - __main__ - INFO - Starting bot...
2025-06-13 20:23:53,046 - discord.client - INFO - logging in using static token
2025-06-13 20:23:53,053 - werkzeug - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:6050
 * Running on http://192.168.86.26:6050
2025-06-13 20:23:53,053 - werkzeug - INFO - [33mPress CTRL+C to quit[0m
2025-06-13 20:23:53,526 - bot - INFO - Setup hook started
2025-06-13 20:23:53,610 - cogs.r6 - INFO - R6Cog loaded and commands synced
2025-06-13 20:23:53,610 - bot - INFO - Loaded extension: cogs.r6
2025-06-13 20:23:53,832 - bot - INFO - Loaded extension: cogs.minecraft
2025-06-13 20:23:53,836 - bot - INFO - Loaded extension: cogs.warframe
2025-06-13 20:23:53,844 - cogs.fun - INFO - Loaded 1 trivia scores
2025-06-13 20:23:53,844 - bot - INFO - Loaded extension: cogs.fun
2025-06-13 20:23:53,852 - bot - INFO - Loaded extension: cogs.alerts
2025-06-13 20:23:53,856 - bot - INFO - Loaded extension: cogs.alert_cmd
2025-06-13 20:23:53,862 - cogs.core - INFO - CoreCog loading: creating aiohttp ClientSession
2025-06-13 20:23:53,862 - bot - INFO - Loaded extension: cogs.core
2025-06-13 20:23:53,864 - bot - INFO - Loaded extension: cogs.owner
2025-06-13 20:23:53,864 - bot - INFO - Loaded extension: cogs.frost
2025-06-13 20:23:53,865 - bot - INFO - App commands before sync: [<discord.app_commands.commands.Group object at 0x7ffedf15f9d0>, <discord.app_commands.commands.Group object at 0x7ffee0fd57d0>, <discord.app_commands.commands.Group object at 0x7ffedf05ab90>, <discord.app_commands.commands.Command object at 0x7ffedf10f6d0>, <discord.app_commands.commands.Command object at 0x7ffedf10e150>, <discord.app_commands.commands.Command object at 0x7ffedf10f810>, <discord.app_commands.commands.Command object at 0x7ffedf10dcd0>, <discord.app_commands.commands.Command object at 0x7ffedf10d690>, <discord.app_commands.commands.Command object at 0x7ffedf10f350>, <discord.app_commands.commands.Command object at 0x7ffedf10fd90>, <discord.app_commands.commands.Command object at 0x7ffedf10fdd0>, <discord.app_commands.commands.Command object at 0x7ffedf10cf50>, <discord.app_commands.commands.Command object at 0x7ffedf10c050>, <discord.app_commands.commands.Command object at 0x7ffedf10f550>, <discord.app_commands.commands.Command object at 0x7ffedf0ca250>, <discord.app_commands.commands.Command object at 0x7ffedf0cbbd0>, <discord.app_commands.commands.Command object at 0x7ffedf0c9110>, <discord.app_commands.commands.Command object at 0x7ffee0fd5cd0>, <discord.app_commands.commands.Command object at 0x7ffedf09da10>, <discord.app_commands.commands.Command object at 0x7ffedf09d950>, <discord.app_commands.commands.Command object at 0x7ffedf09d690>, <discord.app_commands.commands.Command object at 0x7ffedf09e250>, <discord.app_commands.commands.Command object at 0x7ffedf09e450>, <discord.app_commands.commands.Command object at 0x7ffedf09f190>, <discord.app_commands.commands.Command object at 0x7ffedf09fb50>]
2025-06-13 20:23:53,865 - bot - INFO - Force Syncing commands globally...
2025-06-13 20:23:53,993 - bot - INFO - âœ… Commands synced globally
2025-06-13 20:23:53,993 - bot - INFO - Global commands synced. They may take up to 1 hour to appear on Discord clients.
2025-06-13 20:23:54,257 - discord.gateway - INFO - Shard ID None has connected to Gateway (Session ID: 2cbeddd664afa6dedb55343a7260073f).
2025-06-13 20:23:54,257 - bot - INFO - Connected to Discord
2025-06-13 20:23:56,292 - bot - INFO - Logged in as JÃ¤gerBot#6929 (ID: 1376008090968657990)
2025-06-13 20:23:58,908 - discord.ext.commands.bot - ERROR - Ignoring exception in command sync
Traceback (most recent call last):
  File "/home/spoopinatural/jagerbot/venv/lib/python3.11/site-packages/discord/ext/commands/core.py", line 235, in wrapped
    ret = await coro(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/spoopinatural/jagerbot/cogs/owner.py", line 30, in sync_command
    synced = await self.bot.tree.sync(guild=Object(id=gid))
                                            ^^^^^^
NameError: name 'Object' is not defined

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/spoopinatural/jagerbot/venv/lib/python3.11/site-packages/discord/ext/commands/bot.py", line 1366, in invoke
    await ctx.command.invoke(ctx)
  File "/home/spoopinatural/jagerbot/venv/lib/python3.11/site-packages/discord/ext/commands/core.py", line 1029, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/spoopinatural/jagerbot/venv/lib/python3.11/site-packages/discord/ext/commands/core.py", line 244, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: NameError: name 'Object' is not defined
2025-06-13 20:30:42,556 - discord.client - WARNING - PyNaCl is not installed, voice will NOT be supported
2025-06-13 20:30:42,558 - __main__ - INFO - Starting bot...
2025-06-13 20:30:42,558 - discord.client - INFO - logging in using static token
2025-06-13 20:30:42,565 - werkzeug - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:6050
 * Running on http://192.168.86.26:6050
2025-06-13 20:30:42,566 - werkzeug - INFO - [33mPress CTRL+C to quit[0m
2025-06-13 20:30:42,986 - bot - INFO - Setup hook started
2025-06-13 20:30:43,076 - cogs.r6 - INFO - R6Cog loaded and commands synced
2025-06-13 20:30:43,076 - bot - INFO - Loaded extension: cogs.r6
2025-06-13 20:30:43,295 - bot - INFO - Loaded extension: cogs.minecraft
2025-06-13 20:30:43,298 - bot - INFO - Loaded extension: cogs.warframe
2025-06-13 20:30:43,306 - cogs.fun - INFO - Loaded 1 trivia scores
2025-06-13 20:30:43,306 - bot - INFO - Loaded extension: cogs.fun
2025-06-13 20:30:43,314 - bot - INFO - Loaded extension: cogs.alerts
2025-06-13 20:30:43,320 - bot - INFO - Loaded extension: cogs.alert_cmd
2025-06-13 20:30:43,327 - cogs.core - INFO - CoreCog loading: creating aiohttp ClientSession
2025-06-13 20:30:43,327 - bot - INFO - Loaded extension: cogs.core
2025-06-13 20:30:43,328 - bot - INFO - Loaded extension: cogs.owner
2025-06-13 20:30:43,329 - bot - INFO - Loaded extension: cogs.frost
2025-06-13 20:30:43,329 - bot - INFO - App commands before sync: [<discord.app_commands.commands.Group object at 0x7ffebc9bf510>, <discord.app_commands.commands.Group object at 0x7ffebf325b10>, <discord.app_commands.commands.Group object at 0x7ffebc7bb650>, <discord.app_commands.commands.Command object at 0x7ffebc7f1010>, <discord.app_commands.commands.Command object at 0x7ffebc7f0e10>, <discord.app_commands.commands.Command object at 0x7ffebc7f1110>, <discord.app_commands.commands.Command object at 0x7ffebc7f1190>, <discord.app_commands.commands.Command object at 0x7ffebc7f12d0>, <discord.app_commands.commands.Command object at 0x7ffebc7f16d0>, <discord.app_commands.commands.Command object at 0x7ffebc7f1750>, <discord.app_commands.commands.Command object at 0x7ffebc7f1610>, <discord.app_commands.commands.Command object at 0x7ffebc7f17d0>, <discord.app_commands.commands.Command object at 0x7ffebc7f0b10>, <discord.app_commands.commands.Command object at 0x7ffebc7f19d0>, <discord.app_commands.commands.Command object at 0x7ffebc7f3b10>, <discord.app_commands.commands.Command object at 0x7ffebc7f3c90>, <discord.app_commands.commands.Command object at 0x7ffebc7f3e10>, <discord.app_commands.commands.Command object at 0x7ffebc8fd790>, <discord.app_commands.commands.Command object at 0x7ffebc8fe1d0>, <discord.app_commands.commands.Command object at 0x7ffebc8fe2d0>, <discord.app_commands.commands.Command object at 0x7ffebc8fc190>, <discord.app_commands.commands.Command object at 0x7ffebc8fc6d0>, <discord.app_commands.commands.Command object at 0x7ffebc8fd9d0>, <discord.app_commands.commands.Command object at 0x7ffebc8fd8d0>, <discord.app_commands.commands.Command object at 0x7ffebc8fd0d0>]
2025-06-13 20:30:43,329 - bot - INFO - Force Syncing commands globally...
2025-06-13 20:30:43,498 - bot - INFO - âœ… Commands synced globally
2025-06-13 20:30:43,499 - bot - INFO - Global commands synced. They may take up to 1 hour to appear on Discord clients.
2025-06-13 20:30:43,863 - discord.gateway - INFO - Shard ID None has connected to Gateway (Session ID: 6c5a5bee5914d297045ca15a71bb1a1e).
2025-06-13 20:30:43,863 - bot - INFO - Connected to Discord
2025-06-13 20:30:45,888 - bot - INFO - Logged in as JÃ¤gerBot#6929 (ID: 1376008090968657990)
2025-06-13 20:31:09,090 - cogs.owner - INFO - Manually synced commands to all allowed guilds.
2025-06-13 20:33:15,343 - discord.client - WARNING - PyNaCl is not installed, voice will NOT be supported
2025-06-13 20:33:15,344 - __main__ - INFO - Starting bot...
2025-06-13 20:33:15,345 - discord.client - INFO - logging in using static token
2025-06-13 20:33:15,350 - werkzeug - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:6050
 * Running on http://192.168.86.26:6050
2025-06-13 20:33:15,350 - werkzeug - INFO - [33mPress CTRL+C to quit[0m
2025-06-13 20:33:15,980 - bot - INFO - Setup hook started
2025-06-13 20:33:16,156 - cogs.r6 - INFO - R6Cog loaded and commands synced
2025-06-13 20:33:16,157 - bot - INFO - Loaded extension: cogs.r6
2025-06-13 20:33:16,431 - bot - INFO - Loaded extension: cogs.minecraft
2025-06-13 20:33:16,436 - bot - INFO - Loaded extension: cogs.warframe
2025-06-13 20:33:16,443 - cogs.fun - INFO - Loaded 1 trivia scores
2025-06-13 20:33:16,443 - bot - INFO - Loaded extension: cogs.fun
2025-06-13 20:33:16,450 - bot - INFO - Loaded extension: cogs.alerts
2025-06-13 20:33:16,456 - bot - INFO - Loaded extension: cogs.alert_cmd
2025-06-13 20:33:16,463 - cogs.core - INFO - CoreCog loading: creating aiohttp ClientSession
2025-06-13 20:33:16,463 - bot - INFO - Loaded extension: cogs.core
2025-06-13 20:33:16,466 - bot - INFO - Loaded extension: cogs.owner
2025-06-13 20:33:16,467 - bot - INFO - Loaded extension: cogs.frost
2025-06-13 20:33:16,467 - bot - INFO - App commands before sync: [<discord.app_commands.commands.Group object at 0x7ffedcfa5e10>, <discord.app_commands.commands.Group object at 0x7ffedc31fdd0>, <discord.app_commands.commands.Group object at 0x7ffedc1b77d0>, <discord.app_commands.commands.Command object at 0x7ffedcf1d690>, <discord.app_commands.commands.Command object at 0x7ffedc207710>, <discord.app_commands.commands.Command object at 0x7ffedc207690>, <discord.app_commands.commands.Command object at 0x7ffedc207890>, <discord.app_commands.commands.Command object at 0x7ffedc207990>, <discord.app_commands.commands.Command object at 0x7ffedc207950>, <discord.app_commands.commands.Command object at 0x7ffedc207b50>, <discord.app_commands.commands.Command object at 0x7ffedc207bd0>, <discord.app_commands.commands.Command object at 0x7ffedc207c50>, <discord.app_commands.commands.Command object at 0x7ffedc207d90>, <discord.app_commands.commands.Command object at 0x7ffedc207dd0>, <discord.app_commands.commands.Command object at 0x7ffedce08e50>, <discord.app_commands.commands.Command object at 0x7ffedcf018d0>, <discord.app_commands.commands.Command object at 0x7ffedcf012d0>, <discord.app_commands.commands.Command object at 0x7ffedc4545d0>, <discord.app_commands.commands.Command object at 0x7ffedc454790>, <discord.app_commands.commands.Command object at 0x7ffedc375250>, <discord.app_commands.commands.Command object at 0x7ffedc374150>, <discord.app_commands.commands.Command object at 0x7ffedc374e50>, <discord.app_commands.commands.Command object at 0x7ffedc375810>, <discord.app_commands.commands.Command object at 0x7ffedc376d90>, <discord.app_commands.commands.Command object at 0x7ffedc377190>]
2025-06-13 20:33:16,467 - bot - INFO - Force Syncing commands globally...
2025-06-13 20:33:16,589 - bot - INFO - âœ… Commands synced globally
2025-06-13 20:33:16,589 - bot - INFO - Global commands synced. They may take up to 1 hour to appear on Discord clients.
2025-06-13 20:33:16,890 - discord.gateway - INFO - Shard ID None has connected to Gateway (Session ID: f8a54880d7d10a45d6b5ca8e801340ef).
2025-06-13 20:33:16,891 - bot - INFO - Connected to Discord
2025-06-13 20:33:18,926 - bot - INFO - Logged in as JÃ¤gerBot#6929 (ID: 1376008090968657990)
2025-06-13 20:34:58,660 - discord.ext.commands.bot - ERROR - Ignoring exception in command sync
Traceback (most recent call last):
  File "/home/spoopinatural/jagerbot/venv/lib/python3.11/site-packages/discord/ext/commands/core.py", line 235, in wrapped
    ret = await coro(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/spoopinatural/jagerbot/cogs/owner.py", line 19, in sync_command
    cmds = self.bot.tree.get_commands(guild=Object(id=gid))
                                                      ^^^
UnboundLocalError: cannot access local variable 'gid' where it is not associated with a value

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/spoopinatural/jagerbot/venv/lib/python3.11/site-packages/discord/ext/commands/bot.py", line 1366, in invoke
    await ctx.command.invoke(ctx)
  File "/home/spoopinatural/jagerbot/venv/lib/python3.11/site-packages/discord/ext/commands/core.py", line 1029, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/spoopinatural/jagerbot/venv/lib/python3.11/site-packages/discord/ext/commands/core.py", line 244, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: UnboundLocalError: cannot access local variable 'gid' where it is not associated with a value
2025-06-13 20:35:08,376 - discord.ext.commands.bot - ERROR - Ignoring exception in command sync
Traceback (most recent call last):
  File "/home/spoopinatural/jagerbot/venv/lib/python3.11/site-packages/discord/ext/commands/core.py", line 235, in wrapped
    ret = await coro(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/spoopinatural/jagerbot/cogs/owner.py", line 19, in sync_command
    cmds = self.bot.tree.get_commands(guild=Object(id=gid))
                                                      ^^^
UnboundLocalError: cannot access local variable 'gid' where it is not associated with a value

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/spoopinatural/jagerbot/venv/lib/python3.11/site-packages/discord/ext/commands/bot.py", line 1366, in invoke
    await ctx.command.invoke(ctx)
  File "/home/spoopinatural/jagerbot/venv/lib/python3.11/site-packages/discord/ext/commands/core.py", line 1029, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/spoopinatural/jagerbot/venv/lib/python3.11/site-packages/discord/ext/commands/core.py", line 244, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: UnboundLocalError: cannot access local variable 'gid' where it is not associated with a value
2025-06-13 20:38:06,477 - discord.client - WARNING - PyNaCl is not installed, voice will NOT be supported
2025-06-13 20:38:06,478 - __main__ - INFO - Starting bot...
2025-06-13 20:38:06,479 - discord.client - INFO - logging in using static token
2025-06-13 20:38:06,483 - werkzeug - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:6050
 * Running on http://192.168.86.26:6050
2025-06-13 20:38:06,483 - werkzeug - INFO - [33mPress CTRL+C to quit[0m
2025-06-13 20:38:06,875 - bot - INFO - Setup hook started
2025-06-13 20:38:06,950 - cogs.r6 - INFO - R6Cog loaded and commands synced
2025-06-13 20:38:06,950 - bot - INFO - Loaded extension: cogs.r6
2025-06-13 20:38:07,155 - bot - INFO - Loaded extension: cogs.minecraft
2025-06-13 20:38:07,159 - bot - INFO - Loaded extension: cogs.warframe
2025-06-13 20:38:07,167 - cogs.fun - INFO - Loaded 1 trivia scores
2025-06-13 20:38:07,167 - bot - INFO - Loaded extension: cogs.fun
2025-06-13 20:38:07,174 - bot - INFO - Loaded extension: cogs.alerts
2025-06-13 20:38:07,179 - bot - INFO - Loaded extension: cogs.alert_cmd
2025-06-13 20:38:07,186 - cogs.core - INFO - CoreCog loading: creating aiohttp ClientSession
2025-06-13 20:38:07,186 - bot - INFO - Loaded extension: cogs.core
2025-06-13 20:38:07,188 - bot - INFO - Loaded extension: cogs.owner
2025-06-13 20:38:07,189 - bot - INFO - Loaded extension: cogs.frost
2025-06-13 20:38:07,189 - bot - INFO - App commands before sync: [<discord.app_commands.commands.Group object at 0x7fff4f43f510>, <discord.app_commands.commands.Group object at 0x7fff4f32d790>, <discord.app_commands.commands.Group object at 0x7fff4f23b890>, <discord.app_commands.commands.Command object at 0x7fff4f271150>, <discord.app_commands.commands.Command object at 0x7fff4f270f90>, <discord.app_commands.commands.Command object at 0x7fff4f2712d0>, <discord.app_commands.commands.Command object at 0x7fff4f271210>, <discord.app_commands.commands.Command object at 0x7fff4f271450>, <discord.app_commands.commands.Command object at 0x7fff4f271490>, <discord.app_commands.commands.Command object at 0x7fff4f2715d0>, <discord.app_commands.commands.Command object at 0x7fff4f2717d0>, <discord.app_commands.commands.Command object at 0x7fff4f271850>, <discord.app_commands.commands.Command object at 0x7fff4f271890>, <discord.app_commands.commands.Command object at 0x7fff4f271910>, <discord.app_commands.commands.Command object at 0x7fff4f273c50>, <discord.app_commands.commands.Command object at 0x7fff4f273ed0>, <discord.app_commands.commands.Command object at 0x7fff4f272ed0>, <discord.app_commands.commands.Command object at 0x7fff5207b390>, <discord.app_commands.commands.Command object at 0x7fff4f3faed0>, <discord.app_commands.commands.Command object at 0x7fff4f37f810>, <discord.app_commands.commands.Command object at 0x7fff4f37ff10>, <discord.app_commands.commands.Command object at 0x7fff4f37de50>, <discord.app_commands.commands.Command object at 0x7fff4f37c290>, <discord.app_commands.commands.Command object at 0x7fff4f37c810>, <discord.app_commands.commands.Command object at 0x7fff4f37c8d0>]
2025-06-13 20:38:07,189 - bot - INFO - Force Syncing commands globally...
2025-06-13 20:38:07,338 - bot - INFO - âœ… Commands synced globally
2025-06-13 20:38:07,338 - bot - INFO - Global commands synced. They may take up to 1 hour to appear on Discord clients.
2025-06-13 20:38:07,616 - discord.gateway - INFO - Shard ID None has connected to Gateway (Session ID: 92c60e7b847c10e09ded988c217c26ce).
2025-06-13 20:38:07,617 - bot - INFO - Connected to Discord
2025-06-13 20:38:09,643 - bot - INFO - Logged in as JÃ¤gerBot#6929 (ID: 1376008090968657990)
2025-06-13 20:38:37,683 - cogs.owner - INFO - Manually synced commands to all allowed guilds.
2025-06-13 20:47:11,921 - discord.client - WARNING - PyNaCl is not installed, voice will NOT be supported
2025-06-13 20:47:11,922 - __main__ - INFO - Starting bot...
2025-06-13 20:47:11,922 - discord.client - INFO - logging in using static token
2025-06-13 20:47:11,931 - werkzeug - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:6050
 * Running on http://192.168.86.26:6050
2025-06-13 20:47:11,931 - werkzeug - INFO - [33mPress CTRL+C to quit[0m
2025-06-13 20:47:12,619 - bot - INFO - Setup hook started
2025-06-13 20:47:12,697 - cogs.r6 - INFO - R6Cog loaded and commands synced
2025-06-13 20:47:12,697 - bot - INFO - Loaded extension: cogs.r6
2025-06-13 20:47:12,901 - bot - INFO - Loaded extension: cogs.minecraft
2025-06-13 20:47:12,905 - bot - INFO - Loaded extension: cogs.warframe
2025-06-13 20:47:12,912 - cogs.fun - INFO - Loaded 1 trivia scores
2025-06-13 20:47:12,912 - bot - INFO - Loaded extension: cogs.fun
2025-06-13 20:47:12,919 - bot - INFO - Loaded extension: cogs.alerts
2025-06-13 20:47:12,924 - bot - INFO - Loaded extension: cogs.alert_cmd
2025-06-13 20:47:12,931 - cogs.core - INFO - CoreCog loading: creating aiohttp ClientSession
2025-06-13 20:47:12,931 - bot - INFO - Loaded extension: cogs.core
2025-06-13 20:47:12,933 - bot - INFO - Loaded extension: cogs.owner
2025-06-13 20:47:12,934 - bot - INFO - Loaded extension: cogs.frost
2025-06-13 20:47:12,934 - bot - INFO - App commands before sync: [<discord.app_commands.commands.Group object at 0x7ffef837f810>, <discord.app_commands.commands.Group object at 0x7ffef83d2390>, <discord.app_commands.commands.Group object at 0x7ffef9127250>, <discord.app_commands.commands.Command object at 0x7ffef81b15d0>, <discord.app_commands.commands.Command object at 0x7ffef81b1450>, <discord.app_commands.commands.Command object at 0x7ffef81b1710>, <discord.app_commands.commands.Command object at 0x7ffef81b1790>, <discord.app_commands.commands.Command object at 0x7ffef81b1810>, <discord.app_commands.commands.Command object at 0x7ffef81b1950>, <discord.app_commands.commands.Command object at 0x7ffef81b19d0>, <discord.app_commands.commands.Command object at 0x7ffef81b1bd0>, <discord.app_commands.commands.Command object at 0x7ffef81b1d10>, <discord.app_commands.commands.Command object at 0x7ffef81b1d50>, <discord.app_commands.commands.Command object at 0x7ffef81b1e50>, <discord.app_commands.commands.Command object at 0x7ffef8418a50>, <discord.app_commands.commands.Command object at 0x7ffef8418a10>, <discord.app_commands.commands.Command object at 0x7ffef8418f10>, <discord.app_commands.commands.Command object at 0x7ffef82b8550>, <discord.app_commands.commands.Command object at 0x7ffef82b8b90>, <discord.app_commands.commands.Command object at 0x7ffef82b8c50>, <discord.app_commands.commands.Command object at 0x7ffef82b9c90>, <discord.app_commands.commands.Command object at 0x7ffef82b9bd0>, <discord.app_commands.commands.Command object at 0x7ffef82ba690>, <discord.app_commands.commands.Command object at 0x7ffef82ba3d0>, <discord.app_commands.commands.Command object at 0x7ffef82ba510>]
2025-06-13 20:47:12,934 - bot - INFO - Registered global app commands: ['r6', 'mc', 'wf', 'hello', 'quote', 'image', 'clancy', 'longo', '8ball', 'xkcd', 'd20', 'rps', 'trivia', 'score', 'alert', 'listalerts', 'cancelalerts', 'weather', 'currency', 'timezones', 'tzconvert', 'credits', 'date', 'plane', 'info']
2025-06-13 20:47:12,934 - bot - INFO - Force Syncing commands globally...
2025-06-13 20:47:13,039 - bot - INFO - âœ… Commands synced globally
2025-06-13 20:47:13,039 - bot - INFO - Global commands synced. They may take up to 1 hour to appear on Discord clients.
2025-06-13 20:47:13,321 - discord.gateway - INFO - Shard ID None has connected to Gateway (Session ID: 90ef7970c5d78406aabc40c1e1340917).
2025-06-13 20:47:13,322 - bot - INFO - Connected to Discord
2025-06-13 20:47:15,334 - bot - INFO - Logged in as JÃ¤gerBot#6929 (ID: 1376008090968657990)
2025-06-13 20:47:25,706 - cogs.owner - INFO - Manually synced commands to all allowed guilds.
2025-06-13 20:50:11,947 - cogs.owner - INFO - Manually synced 0 commands globally.
2025-06-13 20:50:56,767 - cogs.owner - INFO - Manually synced 0 commands globally.
